# Generated by Django 4.1.6 on 2023-03-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_commentmster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replay',
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.reply'),
        ),
        migrations.DeleteModel(
            name='Commentmster',
        ),
    ]
